### ISSUE TITLE
Fresco Images opactiy cannot be animated

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/nativescript-fresco#25] opened 2016-11-12 21:23 UTC
I use to be able to do this..

`<Image #element class="mark" width="40" height="40"></Image>`

```
@ViewChild("element") element: ElementRef;
element.nativeElement.animate({
                    opacity: 1,
                    duration: 200
                }); 
```

Since switching these image tags to fresco, this no longer works. 

Also noticed I am no longer able to change the opacity of Fresco tags with CSS as well. 
Is there a solution to this?

**Comment by VladimirAmiorkov** [comment] 2016-11-16 16:14
Hi @9thwall ,

I tested the described scenario of animating the opacity of the FrescoDrawee instance and styling it via css and was not able to observe any issues. Both scenarios work correctly.

I added an example that showcases how to do both scenarios and you can take a look at it here:
- XML file - https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/examples/opacity.xml
- TypeScript code - https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/examples/opacity.ts
- CSS file - https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/examples/opacity.css

You can find thee entire examples application [here](https://github.com/NativeScript/nativescript-fresco/tree/master/demo).

Also tested this in NativeScript + Angular 2 application where again was not able to reproduce such an issue. I updated the Angular 2 part of the demo application to include this scenario and you can find it here: [component code](https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/components/app.component.ts) and [html](https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/components/app.component.html). 

Can you try to run the demo app and let me know if you continue to experience issues.

**Comment by VladimirAmiorkov** [comment] 2016-11-28 14:51
Closing the issue for now since I was not able to reproduce the mentioned issue. If anyone continues to experience similar issues let me know.

**Closed as completed by VladimirAmiorkov** 2016-11-28 14:51 UTC
Labels: needs more info
