### ISSUE TITLE
Fresco for background images?

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/nativescript-fresco#24] opened 2016-11-12 20:35 UTC
Hi, I was wondering if I need to use Fresco for full screen background images on the app.
I converted all my other images to the fresco tag and I'm still getting memory crashes so I'm assuming maybe it has to do with the background images. How can I use fresco for this?

Currently I'm just using CSS like this..
Page {
    background-color: #212121;
    background-image: ~/images/background.jpg;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
}

**Comment by VladimirAmiorkov** [comment] 2016-11-16 09:48
HI @9thwall ,

Can you give me a little more information regarding the scenario of your project, how big is the "~/images/background.jpg", is the changing for difference Pages? Maybe there is an issue in the NativeScript Page's `background-image` that we can ask in the [main repo](https://github.com/NativeScript/NativeScript/issues).

To the point, by design the Fresco library is used to display images in and Android application, meaning that you can easily "stretch" the `nativescript-fresco:FrescoDrawee` to fill the entire Page and overlaying it with the other content of your Page. This will require you to implement such layout that allows for such "nesting" of elements. For example an GridLayout with only one row where you place the  `FrescoDrawee` element first and after it the other content that will be over it. This is somewhat a strange layout but it is completely possible just requires some tinkering.

**Comment by 9thwall** [comment] 2016-11-23 19:57
Hi Vladimir!
Thank you for your response. 
The background image I'm using is 768 X 1024 and is 96kb.

I'm gonna try the gridlayout nesting and see if I can make it work.

**Comment by VladimirAmiorkov** [comment] 2016-12-07 13:14
Hi @9thwall ,

Can you confirm the state of this issue, if you feel there is more that the plugin could do to improve such scenarios please let me know.

For now I am closing the issue, feel free to write and reopen it.

**Closed as completed by VladimirAmiorkov** 2016-12-07 13:14 UTC
Labels: help wanted

**Comment by lukaszbarc** [comment] 2017-01-15 22:49
This bug still exist, every time when you have backgroud-image, on every page transition it consumes more and more memory until app finally crash on OOM. OP has a good idea, if this is possible, using fresco for background-images may work much better.
