### ISSUE TITLE
application.onExit,  unable to destroy activity failed?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/nativescript-fresco#3] opened 2016-03-19 07:00 UTC
Hi Team,
     Great work was done. application.onLaunch initialized fresco library. it is facing below issue when application.onExit / backNavigation to exit . Unable to destroy activity and it was crashed immediately.

**Comment by VladimirAmiorkov** [comment] 2016-07-04 10:44
Hi @katturajam ,

Could you give us more details how to reproduce the described issue in order to further investigate it with the latest 1.0.3 version.

**Comment by VladimirAmiorkov** [comment] 2016-08-08 05:29
Closing the issue for now since it cannot be reproduced with the information provided in this issue report. If you manage to reproduce the issue please let me know by providing the required steps.

**Closed as completed by VladimirAmiorkov** 2016-08-08 05:29 UTC
Labels: needs more info
